jobs:
  include:
    - name: build
      script: docker run --rm -v "$(PWD):/app" composer install
    - name: test
      script: docker run -v "$(PWD)":/app php sh -c "cd /app && ./vendor/bin/phpunit"
