language: php

git:
  depth: 1

jobs:
  include:
    - stage: Test
      php: "7.3"
      install: &install
        - travis_retry composer self-update
        - travis_retry composer install --no-interaction --prefer-source --dev
      script:
        - composer test
        - composer lint
    - &test-compatibility
      stage: Compatibility
      php: "7.3"
      os: linux
      <<: *install
      script:
        - composer test
    - <<: *test-compatibility
      php: "5.6"
    - <<: *test-compatibility
      php: "7.2"
    - <<: *test-compatibility
      php: "7.1"
    - stage: Coverage
      name: Coveralls
      php: "7.3"
      <<: *install
      script:
        - composer coveralls
